/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#f6bb80",
        "tertiary-container": "#553001",
        "on-secondary-fixed": "#001e2f",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#8bceff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0b3c5d",
        "surface-container": "#e2efff",
        "on-background": "#0f1d29",
        "outline": "#72777e",
        "on-surface-variant": "#42474e",
        "surface-variant": "#d6e4f5",
        "primary-fixed": "#cee5ff",
        "surface-tint": "#396285",
        "error-container": "#ffdad6",
        "tertiary": "#371d00",
        "on-secondary-container": "#005278",
        "surface-bright": "#f7f9ff",
        "surface-dim": "#cddced",
        "primary": "#00263f",
        "inverse-primary": "#a3cbf2",
        "on-tertiary-fixed-variant": "#663e0e",
        "secondary": "#006492",
        "surface-container-highest": "#d6e4f5",
        "on-tertiary-container": "#ce9760",
        "background": "#f7f9ff",
        "inverse-surface": "#24323f",
        "on-primary-fixed-variant": "#1f4a6c",
        "on-primary-container": "#7fa7cd",
        "outline-variant": "#c2c7ce",
        "surface-container-low": "#edf4ff",
        "on-tertiary-fixed": "#2c1600",
        "on-primary-fixed": "#001d32",
        "on-secondary-fixed-variant": "#004b6f",
        "secondary-container": "#75c6ff",
        "primary-fixed-dim": "#a3cbf2",
        "secondary-fixed": "#c9e6ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdcbd",
        "on-surface": "#0f1d29",
        "on-error": "#ffffff",
        "inverse-on-surface": "#e8f2ff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface": "#f7f9ff",
        "surface-container-high": "#dbeafb",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        md: "24px",
        xs: "4px",
        gutter: "24px",
        sm: "12px",
        base: "8px",
        xl: "80px",
        "margin-mobile": "16px",
        lg: "48px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-xl": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
